<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agreement_model extends CI_Model
{

    public $table = 'trnagreement';
    public $id = 'AgreementId';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('b.AgreementTypeName, c.VendorName, a.ContractNo, a.AgreementId, a.Date, a.ContractPeriodFrom, a.ContractPeriodTo');
        $this->db->join('mstagreementtype b', 'b.AgreementTypeId=a.AgreementTypeId', 'LEFT');
        $this->db->join('mstvendor c', 'c.VendorId=a.VendorId', 'LEFT');
        $this->db->where(array('a.DeletedDate' => NULL));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table.' a')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function viewAgreemntType($id = NULL){
      $sql = "SELECT a.AgreementTypeId, a.AgreementTypeName, CASE WHEN (b.AgreementTypeId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM mstagreementtype a LEFT JOIN (SELECT AgreementTypeId
              FROM trnagreement WHERE AgreementId='$id') b ON a.AgreementTypeId = b.AgreementTypeId
              WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }

    function vendorSelected($id = NULL){
      $sql = "SELECT a.VendorId, a.VendorName, CASE WHEN (b.VendorId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM mstvendor a LEFT JOIN (SELECT VendorId
              FROM trnagreement WHERE AgreementId='$id') b ON a.VendorId = b.VendorId
              WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }

    function viewPaymentType($id = NULL){
      $sql = "SELECT a.PaymentTypeId, a.PaymentTypeName, a.PaymentTypeCode, CASE WHEN (b.PaymentTypeId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM mstpaymenttype a LEFT JOIN (SELECT PaymentTypeId
              FROM trnagreement WHERE AgreementId='$id') b ON a.PaymentTypeId = b.PaymentTypeId
              WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }

    function insertSeqValueDescription($data){
        $this->db->insert('seqvaluedescription', $data);
    }

    function deleteSeqValueDescription($AgreementId){
        $this->db->where('AgreementId', $AgreementId);
        $this->db->delete('seqvaluedescription');
    }

    function getValueDescriptionById($id){
        $this->db->where('AgreementId', $id);
        $this->db->order_by('SortNo', 'ASC');
        return $this->db->get('seqvaluedescription')->result();
    }

    function getReportDetail($id = null){
      $sql = "SELECT a.*, b.VendorName, b.Address1, b.Telp, c.PaymentTypeCode, c.PaymentTypeCode, c.PaymentTypeName, d.AgreementTypeName, d.Pph
              FROM $this->table a
              LEFT JOIN mstvendor b ON a.VendorId=b.VendorId
              LEFT JOIN mstpaymenttype c ON a.PaymentTypeId=c.PaymentTypeId
              LEFT JOIN mstagreementtype d ON a.AgreementTypeId=d.AgreementTypeId
              
              WHERE a.AgreementId='$id'";

      return $this->db->query($sql)->row();
    }

    function getAmountDescription($id = null){
      $this->db->where('AgreementId', $id);
      return $this->db->get('seqvaluedescription')->result();
    }
}

/* End of file Agreement_model.php */
/* Location: ./application/models/Agreement_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 13:59:34 */
/* http://harviacode.com */
