<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proyek_model extends CI_Model
{

    public $table = 'trnproyek';
    public $id = 'ProyekId';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->where(array('DeletedDate' => NULL));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insertSeqProyek($data)
    {
        $this->db->insert('seqproyek', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function deleteSeqProyek($id)
    {
        $this->db->where('proyekid', $id);
        $this->db->delete('seqproyek');
    }

    function viewProyek($id = NULL){
      $sql = "SELECT a.*, b.*, CASE WHEN (b.ProyekId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM mstvendor a LEFT JOIN (SELECT proyekId, vendorid
              FROM seqproyek WHERE proyekid='$id') b ON a.vendorid = b.vendorid WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }

    // function viewTypeProyek($id = NULL){
    //   $sql = "SELECT a.BillTypeId, a.ProyekTypeName, CASE WHEN (b.BillTypeId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
    //           FROM mstproyektype a LEFT JOIN (SELECT BillTypeId
    //           FROM trnproyek WHERE ProyekId='$id') b ON a.BillTypeId = b.BillTypeId
    //           WHERE a.DeletedDate IS NULL";
    //
    //   return $this->db->query($sql)->result();
    // }

}

/* End of file Proyek_model.php */
/* Location: ./application/models/Proyek_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 09:33:17 */
/* http://harviacode.com */
