<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Setting_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    function billType(){
      $sql = "SELECT a.* FROM mstbilltype a WHERE a.DeletedDate is NULL";
      return $this->db->query($sql)->result();
    }

    function billDocument($id = NULL){
      $sql = "SELECT a.DocumentId, a.DocumentName, a.DocumentCode,  
                     CASE WHEN (SELECT b.DocumentId FROM grpbilldocument b WHERE b.DocumentId=a.DocumentId and b.BillTypeId='$id') 
                     THEN 'selected' ELSE '' END AS selected
              FROM mstdocument a 
              WHERE a.DeletedDate IS NULL";
      return $this->db->query($sql)->result();
    }

    function verifycator($ProyekId = NULL){
      $sql = "SELECT a.JabatanId, a.JabatanName, a.JabatanCode, 
                     CASE WHEN (SELECT b.JabatanId FROM grpverificator b WHERE b.JabatanId=a.JabatanId AND b.ProyekId='$ProyekId') 
                     THEN 'selected' ELSE '' END AS selected
              FROM mstjabatan a 
              WHERE a.DeletedDate IS NULL";
      return $this->db->query($sql)->result();
    }

    function deleteBillDocument(){
      return $this->db->query("DELETE FROM grpbilldocument");
    }

    // insert data
    function insertBillDocument($data)
    {
        $this->db->insert('grpbilldocument', $data);
    }

    function deleteVerifycator($ProyekId){
      return $this->db->query("DELETE FROM grpverificator WHERE ProyekId='$ProyekId'");
    }

    function insertVerifycator($data)
    {
        $this->db->insert('grpverificator', $data);
    }

    function isVerificator($JabatanId){
      $this->db->where('JabatanId', $JabatanId);
      return $this->db->get('grpverificator')->row();
    }

    function verifycatorAgreement($Agreement){
      $sql = "SELECT a.JabatanId, a.JabatanName, a.JabatanCode, 
                     CASE WHEN (SELECT b.JabatanId FROM grpverificatoragreement b WHERE b.JabatanId=a.JabatanId AND b.Agreement='$Agreement') 
                     THEN 'selected' ELSE '' END AS selected
              FROM mstjabatan a 
              WHERE a.DeletedDate IS NULL";
      return $this->db->query($sql)->result();
    }

    function deleteVerifycatorAgreement($Agreement){
      return $this->db->query("DELETE FROM grpverificatoragreement WHERE Agreement='$Agreement'");
    }

    function insertVerifycatorAgreement($data)
    {
        $this->db->insert('grpverificatoragreement', $data);
    }
}

/* End of file Proyek_model.php */
/* Location: ./application/models/Proyek_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 09:33:17 */
/* http://harviacode.com */
