<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Spk_model extends CI_Model
{

    public $table = 'trnspk';
    public $id    = 'SpkId';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('a.* , b.PrxoyekName, b.ProyekCode');
        $this->db->join('trnproyek b', 'a.ProyekId=b.ProyekId', 'LEFT');
        $this->db->where(array('a.DeletedDate' => NULL));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table.' a')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $sql = "
          INSERT INTO seqagreementstatus (Agreement, AgreementId, JabatanId)
          (
            SELECT 'SPK', '".$data['SpkId']."', JabatanId FROM grpverificatoragreement a 
            WHERE a.Agreement='SPK'
          )
        ";
        $this->db->query($sql);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function giver1Selected($id = NULL){
      $sql = "SELECT a.id, a.name, c.JabatanName, CASE WHEN (b.Giver1 IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM users a LEFT JOIN (SELECT Giver1
              FROM $this->table WHERE SpkId='$id') b ON a.id = b.Giver1
              LEFT JOIN mstjabatan c ON a.JabatanId=c.JabatanId
              WHERE a.DeletedDate IS NULL AND a.activation='Active'";

      return $this->db->query($sql)->result();
    }

    function giver2Selected($id = NULL){
      $sql = "SELECT a.id, a.name, c.JabatanName, CASE WHEN (b.Giver2 IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM users a LEFT JOIN (SELECT Giver2
              FROM $this->table WHERE SpkId='$id') b ON a.id = b.Giver2
              LEFT JOIN mstjabatan c ON a.JabatanId=c.JabatanId
              WHERE a.DeletedDate IS NULL AND a.activation='Active'";

      return $this->db->query($sql)->result();
    }

    function getSeqSpk($id = NULL){
        $this->db->where('SpkId', $id);
        $this->db->order_by('Sort', 'ASC');
        return $this->db->get('seqspk')->result();
    }

    function spkLanstNoUrut(){
      $sql = "SELECT MAX(CAST(SpkNoUrut AS DECIMAL)) as SpkNoUrut FROM $this->table";
      return $this->db->query($sql)->result();
    }

    function insertSeqSpk($data){
        $this->db->insert('seqspk', $data);
    }

    function deleteSeqSpk($SpkId){
        $this->db->where('SpkId', $SpkId);
        $this->db->delete('seqspk');
    }

    function getDetailSpk($SpkId = NULL){
      $sql = "SELECT a.*, b.name as Giver1, c.JabatanName as JabatanGiver1, 
                     d.name as Giver2, e.JabatanName as JabatanGiver2, f.ProyekCode, f.ProyekName
                FROM trnspk a 
                  LEFT JOIN users b ON a.Giver1=b.id
                  LEFT JOIN mstjabatan c ON b.JabatanId=c.JabatanId
                  LEFT JOIN users d ON a.Giver2=d.id
                  LEFT JOIN mstjabatan e ON d.JabatanId=e.JabatanId
                  LEFT JOIN trnproyek f ON a.ProyekId=f.ProyekId
              WHERE a.SpkId='$SpkId'";
      return $this->db->query($sql)->row();
    }

    function proyekSelected($id = NULL){
      $sql = "SELECT a.ProyekId, a.ProyekCode, a.ProyekName, CASE WHEN (b.ProyekId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM trnproyek a LEFT JOIN (SELECT ProyekId
              FROM $this->table WHERE SpkId='$id') b ON a.ProyekId = b.ProyekId
              WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }
    
    function email_to_verificator($Approval1, $Approval2)
    {
      $sql = "SELECT email FROM users WHERE id IN ('".$Approval1."','".$Approval2."')";
      return $this->db->query($sql)->result_array();
    }

}

/* End of file Spk_model.php */
/* Location: ./application/models/Spk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 13:43:46 */
/* http://harviacode.com */
