<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('users.id, users.name, users.username, users.email, mstjabatan.JabatanCode');
        $this->db->join('mstjabatan', 'users.JabatanId = mstjabatan.JabatanId');
      $this->db->where(array('users.DeletedDate' => NULL));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getDataJabatan($id = NULL)
    {
      $sql = "SELECT a.JabatanId, a.JabatanCode, a.JabatanName,
                CASE WHEN (b.JabatanId IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM mstjabatan a 
              LEFT JOIN (SELECT JabatanId
                FROM users WHERE id='".$id."') b ON a.JabatanId = b.JabatanId
              WHERE a.DeletedDate IS NULL";

      return $this->db->query($sql)->result();
    }

    /********************* User Roles ******************/
    function UserRolesById($id = NULL){
      $this->db->where('RoleId', $id);
      return $this->db->get('roles')->row();
    }

    // insert data
    function InsertUserRoles($data)
    {
      $this->db->insert('roles', $data);
    }

    // update data
    function UpdateUserRoles($id, $data)
    {
      $this->db->where('RoleId', $id);
      $this->db->update('roles', $data);
    }
    /*******************************************************/

    function RoleSelected($id = NULL, $tabel = NULL, $pk = NULL){
      $sql = "SELECT a.RoleId, a.RoleName, CASE WHEN (b.role IS NOT NULL) THEN \"selected = 'selected'\" ELSE 'null' END AS selected
              FROM roles a LEFT JOIN (SELECT role
              FROM $tabel WHERE $pk='$id') b ON a.RoleId = b.role
              WHERE a.Active = 1";

      return $this->db->query($sql)->result();
  }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 12:01:35 */
/* http://harviacode.com */
